package cn.com.realer.pojo;

import cn.com.realer.core.generator.base.BaseModel;

@SuppressWarnings("serial")
public class GabMItem extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_item.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_item.model_id
     *
     * @mbggenerated
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_item.block_id
     *
     * @mbggenerated
     */
    private Integer blockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_item.isleaf
     *
     * @mbggenerated
     */
    private Integer isleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_item.name_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_item.input_type
     *
     * @mbggenerated
     */
    private String inputType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_item.code_
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_item.isdelete
     *
     * @mbggenerated
     */
    private Short isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_item.placehold_
     *
     * @mbggenerated
     */
    private String placehold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_item.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_item.required_
     *
     * @mbggenerated
     */
    private Integer required;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_item.item_type
     *
     * @mbggenerated
     */
    private String itemType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_item.parent_id
     *
     * @return the value of gab_m_item.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_item.parent_id
     *
     * @param parentId the value for gab_m_item.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_item.model_id
     *
     * @return the value of gab_m_item.model_id
     *
     * @mbggenerated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_item.model_id
     *
     * @param modelId the value for gab_m_item.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_item.block_id
     *
     * @return the value of gab_m_item.block_id
     *
     * @mbggenerated
     */
    public Integer getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_item.block_id
     *
     * @param blockId the value for gab_m_item.block_id
     *
     * @mbggenerated
     */
    public void setBlockId(Integer blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_item.isleaf
     *
     * @return the value of gab_m_item.isleaf
     *
     * @mbggenerated
     */
    public Integer getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_item.isleaf
     *
     * @param isleaf the value for gab_m_item.isleaf
     *
     * @mbggenerated
     */
    public void setIsleaf(Integer isleaf) {
        this.isleaf = isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_item.name_
     *
     * @return the value of gab_m_item.name_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_item.name_
     *
     * @param name the value for gab_m_item.name_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_item.input_type
     *
     * @return the value of gab_m_item.input_type
     *
     * @mbggenerated
     */
    public String getInputType() {
        return inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_item.input_type
     *
     * @param inputType the value for gab_m_item.input_type
     *
     * @mbggenerated
     */
    public void setInputType(String inputType) {
        this.inputType = inputType == null ? null : inputType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_item.code_
     *
     * @return the value of gab_m_item.code_
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_item.code_
     *
     * @param code the value for gab_m_item.code_
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_item.isdelete
     *
     * @return the value of gab_m_item.isdelete
     *
     * @mbggenerated
     */
    public Short getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_item.isdelete
     *
     * @param isdelete the value for gab_m_item.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Short isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_item.placehold_
     *
     * @return the value of gab_m_item.placehold_
     *
     * @mbggenerated
     */
    public String getPlacehold() {
        return placehold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_item.placehold_
     *
     * @param placehold the value for gab_m_item.placehold_
     *
     * @mbggenerated
     */
    public void setPlacehold(String placehold) {
        this.placehold = placehold == null ? null : placehold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_item.order_id
     *
     * @return the value of gab_m_item.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_item.order_id
     *
     * @param orderId the value for gab_m_item.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_item.required_
     *
     * @return the value of gab_m_item.required_
     *
     * @mbggenerated
     */
    public Integer getRequired() {
        return required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_item.required_
     *
     * @param required the value for gab_m_item.required_
     *
     * @mbggenerated
     */
    public void setRequired(Integer required) {
        this.required = required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_item.item_type
     *
     * @return the value of gab_m_item.item_type
     *
     * @mbggenerated
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_item.item_type
     *
     * @param itemType the value for gab_m_item.item_type
     *
     * @mbggenerated
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_item
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", parentId=").append(parentId);
        sb.append(", modelId=").append(modelId);
        sb.append(", blockId=").append(blockId);
        sb.append(", isleaf=").append(isleaf);
        sb.append(", name=").append(name);
        sb.append(", inputType=").append(inputType);
        sb.append(", code=").append(code);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", placehold=").append(placehold);
        sb.append(", orderId=").append(orderId);
        sb.append(", required=").append(required);
        sb.append(", itemType=").append(itemType);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_item
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GabMItem other = (GabMItem) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getModelId() == null ? other.getModelId() == null : this.getModelId().equals(other.getModelId()))
            && (this.getBlockId() == null ? other.getBlockId() == null : this.getBlockId().equals(other.getBlockId()))
            && (this.getIsleaf() == null ? other.getIsleaf() == null : this.getIsleaf().equals(other.getIsleaf()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getInputType() == null ? other.getInputType() == null : this.getInputType().equals(other.getInputType()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getIsdelete() == null ? other.getIsdelete() == null : this.getIsdelete().equals(other.getIsdelete()))
            && (this.getPlacehold() == null ? other.getPlacehold() == null : this.getPlacehold().equals(other.getPlacehold()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getRequired() == null ? other.getRequired() == null : this.getRequired().equals(other.getRequired()))
            && (this.getItemType() == null ? other.getItemType() == null : this.getItemType().equals(other.getItemType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_item
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getModelId() == null) ? 0 : getModelId().hashCode());
        result = prime * result + ((getBlockId() == null) ? 0 : getBlockId().hashCode());
        result = prime * result + ((getIsleaf() == null) ? 0 : getIsleaf().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getInputType() == null) ? 0 : getInputType().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getIsdelete() == null) ? 0 : getIsdelete().hashCode());
        result = prime * result + ((getPlacehold() == null) ? 0 : getPlacehold().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getRequired() == null) ? 0 : getRequired().hashCode());
        result = prime * result + ((getItemType() == null) ? 0 : getItemType().hashCode());
        return result;
    }
}