package cn.com.realer.pojo;

import cn.com.realer.core.generator.base.BaseModel;

@SuppressWarnings("serial")
public class GabMOptions extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_options.item_code
     *
     * @mbggenerated
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_options.name_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_options.value_
     *
     * @mbggenerated
     */
    private String value;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_options.self_format
     *
     * @mbggenerated
     */
    private String selfFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_options.hint_
     *
     * @mbggenerated
     */
    private String hint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_options.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_options.item_code
     *
     * @return the value of gab_m_options.item_code
     *
     * @mbggenerated
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_options.item_code
     *
     * @param itemCode the value for gab_m_options.item_code
     *
     * @mbggenerated
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_options.name_
     *
     * @return the value of gab_m_options.name_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_options.name_
     *
     * @param name the value for gab_m_options.name_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_options.value_
     *
     * @return the value of gab_m_options.value_
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_options.value_
     *
     * @param value the value for gab_m_options.value_
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_options.self_format
     *
     * @return the value of gab_m_options.self_format
     *
     * @mbggenerated
     */
    public String getSelfFormat() {
        return selfFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_options.self_format
     *
     * @param selfFormat the value for gab_m_options.self_format
     *
     * @mbggenerated
     */
    public void setSelfFormat(String selfFormat) {
        this.selfFormat = selfFormat == null ? null : selfFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_options.hint_
     *
     * @return the value of gab_m_options.hint_
     *
     * @mbggenerated
     */
    public String getHint() {
        return hint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_options.hint_
     *
     * @param hint the value for gab_m_options.hint_
     *
     * @mbggenerated
     */
    public void setHint(String hint) {
        this.hint = hint == null ? null : hint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_options.order_id
     *
     * @return the value of gab_m_options.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_options.order_id
     *
     * @param orderId the value for gab_m_options.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_options
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", itemCode=").append(itemCode);
        sb.append(", name=").append(name);
        sb.append(", value=").append(value);
        sb.append(", selfFormat=").append(selfFormat);
        sb.append(", hint=").append(hint);
        sb.append(", orderId=").append(orderId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_options
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GabMOptions other = (GabMOptions) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getItemCode() == null ? other.getItemCode() == null : this.getItemCode().equals(other.getItemCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getIsdelete() == null ? other.getIsdelete() == null : this.getIsdelete().equals(other.getIsdelete()))
            && (this.getSelfFormat() == null ? other.getSelfFormat() == null : this.getSelfFormat().equals(other.getSelfFormat()))
            && (this.getHint() == null ? other.getHint() == null : this.getHint().equals(other.getHint()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_options
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getItemCode() == null) ? 0 : getItemCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getIsdelete() == null) ? 0 : getIsdelete().hashCode());
        result = prime * result + ((getSelfFormat() == null) ? 0 : getSelfFormat().hashCode());
        result = prime * result + ((getHint() == null) ? 0 : getHint().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        return result;
    }
}