package cn.com.realer.pojo;

import cn.com.realer.core.generator.base.BaseModel;

@SuppressWarnings("serial")
public class GabMBlockStatus extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_block_status.police_id
     *
     * @mbggenerated
     */
    private Integer policeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_block_status.theme_id
     *
     * @mbggenerated
     */
    private Integer themeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_block_status.block_id
     *
     * @mbggenerated
     */
    private Integer blockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_m_block_status.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_block_status.police_id
     *
     * @return the value of gab_m_block_status.police_id
     *
     * @mbggenerated
     */
    public Integer getPoliceId() {
        return policeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_block_status.police_id
     *
     * @param policeId the value for gab_m_block_status.police_id
     *
     * @mbggenerated
     */
    public void setPoliceId(Integer policeId) {
        this.policeId = policeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_block_status.theme_id
     *
     * @return the value of gab_m_block_status.theme_id
     *
     * @mbggenerated
     */
    public Integer getThemeId() {
        return themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_block_status.theme_id
     *
     * @param themeId the value for gab_m_block_status.theme_id
     *
     * @mbggenerated
     */
    public void setThemeId(Integer themeId) {
        this.themeId = themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_block_status.block_id
     *
     * @return the value of gab_m_block_status.block_id
     *
     * @mbggenerated
     */
    public Integer getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_block_status.block_id
     *
     * @param blockId the value for gab_m_block_status.block_id
     *
     * @mbggenerated
     */
    public void setBlockId(Integer blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_m_block_status.status
     *
     * @return the value of gab_m_block_status.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_m_block_status.status
     *
     * @param status the value for gab_m_block_status.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_block_status
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", policeId=").append(policeId);
        sb.append(", themeId=").append(themeId);
        sb.append(", blockId=").append(blockId);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_block_status
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GabMBlockStatus other = (GabMBlockStatus) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPoliceId() == null ? other.getPoliceId() == null : this.getPoliceId().equals(other.getPoliceId()))
            && (this.getThemeId() == null ? other.getThemeId() == null : this.getThemeId().equals(other.getThemeId()))
            && (this.getBlockId() == null ? other.getBlockId() == null : this.getBlockId().equals(other.getBlockId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getIsdelete() == null ? other.getIsdelete() == null : this.getIsdelete().equals(other.getIsdelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_block_status
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPoliceId() == null) ? 0 : getPoliceId().hashCode());
        result = prime * result + ((getThemeId() == null) ? 0 : getThemeId().hashCode());
        result = prime * result + ((getBlockId() == null) ? 0 : getBlockId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getIsdelete() == null) ? 0 : getIsdelete().hashCode());
        return result;
    }
}