package cn.com.realer.pojo;

import cn.com.realer.core.generator.base.BaseModel;
import java.math.BigDecimal;

@SuppressWarnings("serial")
public class GabUPolice extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.name_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.location_id
     *
     * @mbggenerated
     */
    private Integer locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.address_
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.erea_
     *
     * @mbggenerated
     */
    private BigDecimal erea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.header_name
     *
     * @mbggenerated
     */
    private String headerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.header_phone
     *
     * @mbggenerated
     */
    private String headerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.telephone_
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.password_
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.active_status
     *
     * @mbggenerated
     */
    private Short activeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.province_
     *
     * @mbggenerated
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.city_
     *
     * @mbggenerated
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.area_
     *
     * @mbggenerated
     */
    private Integer area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.jurisdiction_
     *
     * @mbggenerated
     */
    private Integer jurisdiction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.residence_
     *
     * @mbggenerated
     */
    private Integer residence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.property_
     *
     * @mbggenerated
     */
    private Integer property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.active_code
     *
     * @mbggenerated
     */
    private String activeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.rating_
     *
     * @mbggenerated
     */
    private Integer rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police.email_
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.name_
     *
     * @return the value of gab_u_police.name_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.name_
     *
     * @param name the value for gab_u_police.name_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.location_id
     *
     * @return the value of gab_u_police.location_id
     *
     * @mbggenerated
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.location_id
     *
     * @param locationId the value for gab_u_police.location_id
     *
     * @mbggenerated
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.address_
     *
     * @return the value of gab_u_police.address_
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.address_
     *
     * @param address the value for gab_u_police.address_
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.category_id
     *
     * @return the value of gab_u_police.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.category_id
     *
     * @param categoryId the value for gab_u_police.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.erea_
     *
     * @return the value of gab_u_police.erea_
     *
     * @mbggenerated
     */
    public BigDecimal getErea() {
        return erea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.erea_
     *
     * @param erea the value for gab_u_police.erea_
     *
     * @mbggenerated
     */
    public void setErea(BigDecimal erea) {
        this.erea = erea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.header_name
     *
     * @return the value of gab_u_police.header_name
     *
     * @mbggenerated
     */
    public String getHeaderName() {
        return headerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.header_name
     *
     * @param headerName the value for gab_u_police.header_name
     *
     * @mbggenerated
     */
    public void setHeaderName(String headerName) {
        this.headerName = headerName == null ? null : headerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.header_phone
     *
     * @return the value of gab_u_police.header_phone
     *
     * @mbggenerated
     */
    public String getHeaderPhone() {
        return headerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.header_phone
     *
     * @param headerPhone the value for gab_u_police.header_phone
     *
     * @mbggenerated
     */
    public void setHeaderPhone(String headerPhone) {
        this.headerPhone = headerPhone == null ? null : headerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.telephone_
     *
     * @return the value of gab_u_police.telephone_
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.telephone_
     *
     * @param telephone the value for gab_u_police.telephone_
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.password_
     *
     * @return the value of gab_u_police.password_
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.password_
     *
     * @param password the value for gab_u_police.password_
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.status
     *
     * @return the value of gab_u_police.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.status
     *
     * @param status the value for gab_u_police.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.active_status
     *
     * @return the value of gab_u_police.active_status
     *
     * @mbggenerated
     */
    public Short getActiveStatus() {
        return activeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.active_status
     *
     * @param activeStatus the value for gab_u_police.active_status
     *
     * @mbggenerated
     */
    public void setActiveStatus(Short activeStatus) {
        this.activeStatus = activeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.position
     *
     * @return the value of gab_u_police.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.position
     *
     * @param position the value for gab_u_police.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.province_
     *
     * @return the value of gab_u_police.province_
     *
     * @mbggenerated
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.province_
     *
     * @param province the value for gab_u_police.province_
     *
     * @mbggenerated
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.city_
     *
     * @return the value of gab_u_police.city_
     *
     * @mbggenerated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.city_
     *
     * @param city the value for gab_u_police.city_
     *
     * @mbggenerated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.area_
     *
     * @return the value of gab_u_police.area_
     *
     * @mbggenerated
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.area_
     *
     * @param area the value for gab_u_police.area_
     *
     * @mbggenerated
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.jurisdiction_
     *
     * @return the value of gab_u_police.jurisdiction_
     *
     * @mbggenerated
     */
    public Integer getJurisdiction() {
        return jurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.jurisdiction_
     *
     * @param jurisdiction the value for gab_u_police.jurisdiction_
     *
     * @mbggenerated
     */
    public void setJurisdiction(Integer jurisdiction) {
        this.jurisdiction = jurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.residence_
     *
     * @return the value of gab_u_police.residence_
     *
     * @mbggenerated
     */
    public Integer getResidence() {
        return residence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.residence_
     *
     * @param residence the value for gab_u_police.residence_
     *
     * @mbggenerated
     */
    public void setResidence(Integer residence) {
        this.residence = residence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.property_
     *
     * @return the value of gab_u_police.property_
     *
     * @mbggenerated
     */
    public Integer getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.property_
     *
     * @param property the value for gab_u_police.property_
     *
     * @mbggenerated
     */
    public void setProperty(Integer property) {
        this.property = property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.active_code
     *
     * @return the value of gab_u_police.active_code
     *
     * @mbggenerated
     */
    public String getActiveCode() {
        return activeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.active_code
     *
     * @param activeCode the value for gab_u_police.active_code
     *
     * @mbggenerated
     */
    public void setActiveCode(String activeCode) {
        this.activeCode = activeCode == null ? null : activeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.rating_
     *
     * @return the value of gab_u_police.rating_
     *
     * @mbggenerated
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.rating_
     *
     * @param rating the value for gab_u_police.rating_
     *
     * @mbggenerated
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police.email_
     *
     * @return the value of gab_u_police.email_
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police.email_
     *
     * @param email the value for gab_u_police.email_
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", locationId=").append(locationId);
        sb.append(", address=").append(address);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", erea=").append(erea);
        sb.append(", headerName=").append(headerName);
        sb.append(", headerPhone=").append(headerPhone);
        sb.append(", telephone=").append(telephone);
        sb.append(", password=").append(password);
        sb.append(", status=").append(status);
        sb.append(", activeStatus=").append(activeStatus);
        sb.append(", position=").append(position);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", area=").append(area);
        sb.append(", jurisdiction=").append(jurisdiction);
        sb.append(", residence=").append(residence);
        sb.append(", property=").append(property);
        sb.append(", activeCode=").append(activeCode);
        sb.append(", rating=").append(rating);
        sb.append(", email=").append(email);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GabUPolice other = (GabUPolice) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getLocationId() == null ? other.getLocationId() == null : this.getLocationId().equals(other.getLocationId()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getCategoryId() == null ? other.getCategoryId() == null : this.getCategoryId().equals(other.getCategoryId()))
            && (this.getErea() == null ? other.getErea() == null : this.getErea().equals(other.getErea()))
            && (this.getHeaderName() == null ? other.getHeaderName() == null : this.getHeaderName().equals(other.getHeaderName()))
            && (this.getHeaderPhone() == null ? other.getHeaderPhone() == null : this.getHeaderPhone().equals(other.getHeaderPhone()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getIsdelete() == null ? other.getIsdelete() == null : this.getIsdelete().equals(other.getIsdelete()))
            && (this.getActiveStatus() == null ? other.getActiveStatus() == null : this.getActiveStatus().equals(other.getActiveStatus()))
            && (this.getPosition() == null ? other.getPosition() == null : this.getPosition().equals(other.getPosition()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
            && (this.getJurisdiction() == null ? other.getJurisdiction() == null : this.getJurisdiction().equals(other.getJurisdiction()))
            && (this.getResidence() == null ? other.getResidence() == null : this.getResidence().equals(other.getResidence()))
            && (this.getProperty() == null ? other.getProperty() == null : this.getProperty().equals(other.getProperty()))
            && (this.getActiveCode() == null ? other.getActiveCode() == null : this.getActiveCode().equals(other.getActiveCode()))
            && (this.getRating() == null ? other.getRating() == null : this.getRating().equals(other.getRating()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getLocationId() == null) ? 0 : getLocationId().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getCategoryId() == null) ? 0 : getCategoryId().hashCode());
        result = prime * result + ((getErea() == null) ? 0 : getErea().hashCode());
        result = prime * result + ((getHeaderName() == null) ? 0 : getHeaderName().hashCode());
        result = prime * result + ((getHeaderPhone() == null) ? 0 : getHeaderPhone().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getIsdelete() == null) ? 0 : getIsdelete().hashCode());
        result = prime * result + ((getActiveStatus() == null) ? 0 : getActiveStatus().hashCode());
        result = prime * result + ((getPosition() == null) ? 0 : getPosition().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getJurisdiction() == null) ? 0 : getJurisdiction().hashCode());
        result = prime * result + ((getResidence() == null) ? 0 : getResidence().hashCode());
        result = prime * result + ((getProperty() == null) ? 0 : getProperty().hashCode());
        result = prime * result + ((getActiveCode() == null) ? 0 : getActiveCode().hashCode());
        result = prime * result + ((getRating() == null) ? 0 : getRating().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        return result;
    }
}