package cn.com.realer.pojo;

import cn.com.realer.core.generator.base.BaseModel;

@SuppressWarnings("serial")
public class GabUValueDesc extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_value_desc.police_id
     *
     * @mbggenerated
     */
    private Integer policeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_value_desc.theme_id
     *
     * @mbggenerated
     */
    private Integer themeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_value_desc.item_id
     *
     * @mbggenerated
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_value_desc.name_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_value_desc.value_
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_value_desc.number_
     *
     * @mbggenerated
     */
    private Integer number;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_value_desc.block_id
     *
     * @mbggenerated
     */
    private Integer blockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_value_desc.options_id
     *
     * @mbggenerated
     */
    private Integer optionsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_value_desc.police_id
     *
     * @return the value of gab_u_value_desc.police_id
     *
     * @mbggenerated
     */
    public Integer getPoliceId() {
        return policeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_value_desc.police_id
     *
     * @param policeId the value for gab_u_value_desc.police_id
     *
     * @mbggenerated
     */
    public void setPoliceId(Integer policeId) {
        this.policeId = policeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_value_desc.theme_id
     *
     * @return the value of gab_u_value_desc.theme_id
     *
     * @mbggenerated
     */
    public Integer getThemeId() {
        return themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_value_desc.theme_id
     *
     * @param themeId the value for gab_u_value_desc.theme_id
     *
     * @mbggenerated
     */
    public void setThemeId(Integer themeId) {
        this.themeId = themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_value_desc.item_id
     *
     * @return the value of gab_u_value_desc.item_id
     *
     * @mbggenerated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_value_desc.item_id
     *
     * @param itemId the value for gab_u_value_desc.item_id
     *
     * @mbggenerated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_value_desc.name_
     *
     * @return the value of gab_u_value_desc.name_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_value_desc.name_
     *
     * @param name the value for gab_u_value_desc.name_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_value_desc.value_
     *
     * @return the value of gab_u_value_desc.value_
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_value_desc.value_
     *
     * @param value the value for gab_u_value_desc.value_
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_value_desc.number_
     *
     * @return the value of gab_u_value_desc.number_
     *
     * @mbggenerated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_value_desc.number_
     *
     * @param number the value for gab_u_value_desc.number_
     *
     * @mbggenerated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_value_desc.block_id
     *
     * @return the value of gab_u_value_desc.block_id
     *
     * @mbggenerated
     */
    public Integer getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_value_desc.block_id
     *
     * @param blockId the value for gab_u_value_desc.block_id
     *
     * @mbggenerated
     */
    public void setBlockId(Integer blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_value_desc.options_id
     *
     * @return the value of gab_u_value_desc.options_id
     *
     * @mbggenerated
     */
    public Integer getOptionsId() {
        return optionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_value_desc.options_id
     *
     * @param optionsId the value for gab_u_value_desc.options_id
     *
     * @mbggenerated
     */
    public void setOptionsId(Integer optionsId) {
        this.optionsId = optionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_value_desc
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", policeId=").append(policeId);
        sb.append(", themeId=").append(themeId);
        sb.append(", itemId=").append(itemId);
        sb.append(", name=").append(name);
        sb.append(", value=").append(value);
        sb.append(", number=").append(number);
        sb.append(", blockId=").append(blockId);
        sb.append(", optionsId=").append(optionsId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_value_desc
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GabUValueDesc other = (GabUValueDesc) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPoliceId() == null ? other.getPoliceId() == null : this.getPoliceId().equals(other.getPoliceId()))
            && (this.getThemeId() == null ? other.getThemeId() == null : this.getThemeId().equals(other.getThemeId()))
            && (this.getItemId() == null ? other.getItemId() == null : this.getItemId().equals(other.getItemId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getIsdelete() == null ? other.getIsdelete() == null : this.getIsdelete().equals(other.getIsdelete()))
            && (this.getBlockId() == null ? other.getBlockId() == null : this.getBlockId().equals(other.getBlockId()))
            && (this.getOptionsId() == null ? other.getOptionsId() == null : this.getOptionsId().equals(other.getOptionsId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_value_desc
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPoliceId() == null) ? 0 : getPoliceId().hashCode());
        result = prime * result + ((getThemeId() == null) ? 0 : getThemeId().hashCode());
        result = prime * result + ((getItemId() == null) ? 0 : getItemId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getIsdelete() == null) ? 0 : getIsdelete().hashCode());
        result = prime * result + ((getBlockId() == null) ? 0 : getBlockId().hashCode());
        result = prime * result + ((getOptionsId() == null) ? 0 : getOptionsId().hashCode());
        return result;
    }
}