package cn.com.realer.pojo;

import cn.com.realer.core.generator.base.BaseModel;
import java.util.Date;

@SuppressWarnings("serial")
public class GabUPoliceTheme extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police_theme.police_id
     *
     * @mbggenerated
     */
    private Integer policeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police_theme.model_id
     *
     * @mbggenerated
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police_theme.theme_id
     *
     * @mbggenerated
     */
    private Integer themeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police_theme.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police_theme.auditor_
     *
     * @mbggenerated
     */
    private String auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police_theme.audit_time
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gab_u_police_theme.audit_desc
     *
     * @mbggenerated
     */
    private String auditDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police_theme.police_id
     *
     * @return the value of gab_u_police_theme.police_id
     *
     * @mbggenerated
     */
    public Integer getPoliceId() {
        return policeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police_theme.police_id
     *
     * @param policeId the value for gab_u_police_theme.police_id
     *
     * @mbggenerated
     */
    public void setPoliceId(Integer policeId) {
        this.policeId = policeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police_theme.model_id
     *
     * @return the value of gab_u_police_theme.model_id
     *
     * @mbggenerated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police_theme.model_id
     *
     * @param modelId the value for gab_u_police_theme.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police_theme.theme_id
     *
     * @return the value of gab_u_police_theme.theme_id
     *
     * @mbggenerated
     */
    public Integer getThemeId() {
        return themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police_theme.theme_id
     *
     * @param themeId the value for gab_u_police_theme.theme_id
     *
     * @mbggenerated
     */
    public void setThemeId(Integer themeId) {
        this.themeId = themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police_theme.status
     *
     * @return the value of gab_u_police_theme.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police_theme.status
     *
     * @param status the value for gab_u_police_theme.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police_theme.auditor_
     *
     * @return the value of gab_u_police_theme.auditor_
     *
     * @mbggenerated
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police_theme.auditor_
     *
     * @param auditor the value for gab_u_police_theme.auditor_
     *
     * @mbggenerated
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police_theme.audit_time
     *
     * @return the value of gab_u_police_theme.audit_time
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police_theme.audit_time
     *
     * @param auditTime the value for gab_u_police_theme.audit_time
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gab_u_police_theme.audit_desc
     *
     * @return the value of gab_u_police_theme.audit_desc
     *
     * @mbggenerated
     */
    public String getAuditDesc() {
        return auditDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gab_u_police_theme.audit_desc
     *
     * @param auditDesc the value for gab_u_police_theme.audit_desc
     *
     * @mbggenerated
     */
    public void setAuditDesc(String auditDesc) {
        this.auditDesc = auditDesc == null ? null : auditDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police_theme
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", policeId=").append(policeId);
        sb.append(", modelId=").append(modelId);
        sb.append(", themeId=").append(themeId);
        sb.append(", status=").append(status);
        sb.append(", auditor=").append(auditor);
        sb.append(", auditTime=").append(auditTime);
        sb.append(", auditDesc=").append(auditDesc);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police_theme
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GabUPoliceTheme other = (GabUPoliceTheme) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPoliceId() == null ? other.getPoliceId() == null : this.getPoliceId().equals(other.getPoliceId()))
            && (this.getModelId() == null ? other.getModelId() == null : this.getModelId().equals(other.getModelId()))
            && (this.getThemeId() == null ? other.getThemeId() == null : this.getThemeId().equals(other.getThemeId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getIsdelete() == null ? other.getIsdelete() == null : this.getIsdelete().equals(other.getIsdelete()))
            && (this.getAuditor() == null ? other.getAuditor() == null : this.getAuditor().equals(other.getAuditor()))
            && (this.getAuditTime() == null ? other.getAuditTime() == null : this.getAuditTime().equals(other.getAuditTime()))
            && (this.getAuditDesc() == null ? other.getAuditDesc() == null : this.getAuditDesc().equals(other.getAuditDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police_theme
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPoliceId() == null) ? 0 : getPoliceId().hashCode());
        result = prime * result + ((getModelId() == null) ? 0 : getModelId().hashCode());
        result = prime * result + ((getThemeId() == null) ? 0 : getThemeId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getIsdelete() == null) ? 0 : getIsdelete().hashCode());
        result = prime * result + ((getAuditor() == null) ? 0 : getAuditor().hashCode());
        result = prime * result + ((getAuditTime() == null) ? 0 : getAuditTime().hashCode());
        result = prime * result + ((getAuditDesc() == null) ? 0 : getAuditDesc().hashCode());
        return result;
    }
}