package cn.com.realer.dao.generator.u;

import cn.com.realer.core.generator.base.BaseMapper;
import cn.com.realer.pojo.GabUPermission;
import java.util.List;

public interface GabUPermissionMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_permission
     *
     * @mbggenerated
     */
    int insert(GabUPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_permission
     *
     * @mbggenerated
     */
    GabUPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_permission
     *
     * @mbggenerated
     */
    List<GabUPermission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GabUPermission record);
}