package cn.com.realer.dao.generator.u;

import cn.com.realer.core.generator.base.BaseMapper;
import cn.com.realer.pojo.GabUPolice;
import java.util.List;

public interface GabUPoliceMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police
     *
     * @mbggenerated
     */
    int insert(GabUPolice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police
     *
     * @mbggenerated
     */
    GabUPolice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police
     *
     * @mbggenerated
     */
    List<GabUPolice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GabUPolice record);
}