package cn.com.realer.dao.generator.u;

import cn.com.realer.core.generator.base.BaseMapper;
import cn.com.realer.pojo.GabUValueDesc;
import java.util.List;

public interface GabUValueDescMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_value_desc
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_value_desc
     *
     * @mbggenerated
     */
    int insert(GabUValueDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_value_desc
     *
     * @mbggenerated
     */
    GabUValueDesc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_value_desc
     *
     * @mbggenerated
     */
    List<GabUValueDesc> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_value_desc
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GabUValueDesc record);
}