package cn.com.realer.dao.generator.u;

import cn.com.realer.core.generator.base.BaseMapper;
import cn.com.realer.pojo.GabUPoliceTheme;
import java.util.List;

public interface GabUPoliceThemeMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police_theme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police_theme
     *
     * @mbggenerated
     */
    int insert(GabUPoliceTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police_theme
     *
     * @mbggenerated
     */
    GabUPoliceTheme selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police_theme
     *
     * @mbggenerated
     */
    List<GabUPoliceTheme> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_u_police_theme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GabUPoliceTheme record);
}