package cn.com.realer.dao.generator.m;

import cn.com.realer.core.generator.base.BaseMapper;
import cn.com.realer.pojo.GabMCategory;
import java.util.List;

public interface GabMCategoryMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_category
     *
     * @mbggenerated
     */
    int insert(GabMCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_category
     *
     * @mbggenerated
     */
    GabMCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_category
     *
     * @mbggenerated
     */
    List<GabMCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GabMCategory record);
}