package cn.com.realer.dao.generator.m;

import cn.com.realer.core.generator.base.BaseMapper;
import cn.com.realer.pojo.GabMItem;
import java.util.List;

public interface GabMItemMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_item
     *
     * @mbggenerated
     */
    int insert(GabMItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_item
     *
     * @mbggenerated
     */
    GabMItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_item
     *
     * @mbggenerated
     */
    List<GabMItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GabMItem record);
}