package cn.com.realer.dao.generator.m;

import cn.com.realer.core.generator.base.BaseMapper;
import cn.com.realer.pojo.GabMModel;
import java.util.List;

public interface GabMModelMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_model
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_model
     *
     * @mbggenerated
     */
    int insert(GabMModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_model
     *
     * @mbggenerated
     */
    GabMModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_model
     *
     * @mbggenerated
     */
    List<GabMModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_model
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GabMModel record);
}