package cn.com.realer.dao.generator.m;

import cn.com.realer.core.generator.base.BaseMapper;
import cn.com.realer.pojo.GabMTheme;
import java.util.List;

public interface GabMThemeMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_theme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_theme
     *
     * @mbggenerated
     */
    int insert(GabMTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_theme
     *
     * @mbggenerated
     */
    GabMTheme selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_theme
     *
     * @mbggenerated
     */
    List<GabMTheme> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_theme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GabMTheme record);
}