package cn.com.realer.dao.generator.m;

import cn.com.realer.core.generator.base.BaseMapper;
import cn.com.realer.pojo.GabMBlock;
import java.util.List;

public interface GabMBlockMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_block
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_block
     *
     * @mbggenerated
     */
    int insert(GabMBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_block
     *
     * @mbggenerated
     */
    GabMBlock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_block
     *
     * @mbggenerated
     */
    List<GabMBlock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_block
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GabMBlock record);
}