package cn.com.realer.dao.generator.m;

import cn.com.realer.core.generator.base.BaseMapper;
import cn.com.realer.pojo.GabMBlockStatus;
import java.util.List;

public interface GabMBlockStatusMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_block_status
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_block_status
     *
     * @mbggenerated
     */
    int insert(GabMBlockStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_block_status
     *
     * @mbggenerated
     */
    GabMBlockStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_block_status
     *
     * @mbggenerated
     */
    List<GabMBlockStatus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_block_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GabMBlockStatus record);
}