package cn.com.realer.dao.generator.m;

import cn.com.realer.core.generator.base.BaseMapper;
import cn.com.realer.pojo.GabMLocation;
import java.util.List;

public interface GabMLocationMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_location
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_location
     *
     * @mbggenerated
     */
    int insert(GabMLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_location
     *
     * @mbggenerated
     */
    GabMLocation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_location
     *
     * @mbggenerated
     */
    List<GabMLocation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gab_m_location
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GabMLocation record);
}